<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Manueller_Betrieb" Id="{ac3c5180-7042-481e-a944-4bd75763f607}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Manueller_Betrieb
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Manueller_Betrieb">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>