<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="VISU" Id="{8c79f4c1-9909-4056-b77f-242d9e2e78d9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK VISU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="VISU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>