<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Warmlauf" Id="{324c2e16-6603-4026-8ed3-6aedaaab5116}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Warmlauf
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Warmlauf">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>