<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{14b975ff-daf1-4eb0-a595-be74e665f929}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Saegeautomat : Saegeautomat;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Saegeautomat();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>